# http://module-build.sourceforge.net/META-spec.html
#
name:         MIME-Base16
version:      1.2
version_from: Base16.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
